name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install pytest

    - name: Run tests
      run: pytest

    - name: Login Docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: edwinpaul23/python-app:latest
